server:
  port: 3030
  servlet.context-path : /generator/api
spring:
  datasource:
    name: test
    url: jdbc:mysql://10.0.20.108:3306/baofoo_datamanager
    username: baofoo_api
    password: baofoo_api@123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  ## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:mappers/**/*Mapper.xml
  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.baofoo.generator.model
  # 注意：对应实体类的路径
  #pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
        config: classpath:logback-core.xml
#rootPath: /usr/local/generationZip

rootPath: D:/generationZip

springInitializrUrl : http://10.0.19.248:8082/starter.zip
springInitializrDependenciesUrl : http://10.0.19.248:8082/ui/dependencies?version=2.1.1.RELEASE
fileServer : 10.0.19.47:7080

